

SYMBOLS = ["BTCUSDT", "ETHBTC", "XRPBTC", "BCCBTC", "LTCBTC", "EOSBTC", "ADABTC", "XLMBTC", "NEOBTC", "IOTABTC", \
             "XMRBTC", "DASHBTC", "XEMBTC", "TRXBTC", "VENBTC", "ETCBTC", "BNBBTC", "QTUMBTC", "OMGBTC", "XVGBTC", \
             "LSKBTC", "ONTBTC", "ICXBTC", "ZECBTC", "NANOBTC", "BTGBTC", "STEEMBTC", "WANBTC", "PPTBTC", "BTSBTC", \
             "DGDBTC", "STRATBTC", "WAVESBTC", "ZILBTC"]


